# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
















































words = [
    # Polish
    'kurwa',
    'cipa',
    'pizda',
    'huj',
    'pierdol',
    'dziwka',

    # English
    'fuck',
    'bitch',
    'retard',
    'nigg',

    # Spanish (?)
    'puta',
]




















































# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON
# DO NOT OPEN THIS MODULE ON THE STREAM YOU IRRATIONAL PERSON

